### ISSUE TITLE
arona获取nga图楼信息失败

### ISSUE THREAD

**Issue by LeonCCCCC** [diyigemt/arona#32]
重新配置arona后，使用和之前相同的nga.yml配置信息却无法正常获取图楼
报错为：`2023-07-19 22:14:11 W/blue-archive-arona: arona获取nga图楼信息失败,请检查配置文件是否有误`
已经检查过uid和cid均是最新状态，其它的配置信息也未作更改
请问是因为泥潭的原因所以导致没法正常爬取了吗？

具体的nga.yml配置信息如下所示：
```
# 你自己的nga uid
uid: 425XXXXX
# 登录后产生的cookie, 可以从名叫"ngaPassportCid"的cookie中获取
cid: X9hign7ojuvmc95qbinss6uquucrnf77XXXXXXXX
# 扫描周期(单位min)
checkInterval: 30
# 数据源(主站寄了的时候可以换一下),可选"MAIN"(主站)和"SUB"(备用站)
source: SUB
# 要监听的发送者uid以及nga昵称
watch: 
  42382305: xiwang399
  40785736: 安kuzuha
  64124793: 星泠鑫
# 已发送的缓存
cache: 
  - first: 18
    second: 703214606
  - first: 18
    second: 703211956
  - first: 18
    second: 703210062
  - first: 18
    second: 703209647
  - first: 18
    second: 703204948
  - first: 18
    second: 703040763
  - first: 18
    second: 703012912
  - first: 18
    second: 702992382
```
