### ISSUE TITLE
NGA监听特定用户时出现图片转发不全的问题

### ISSUE THREAD

**Issue by LeonCCCCC** [diyigemt/arona#38]
在`nga.yml`中添加了另外如下所示的几个用户，其中`Haremsupervisor`用户出现了图片转发不全的现象，表现为只有第一句话以及第一张图。
#### 这是正常监听的额外用户
![_0c1eec9d596458b3ac73870656a44af4_-710612491_Screenshot_20230809_163514](https://github.com/diyigemt/arona/assets/89019933/f0631929-c4e9-45d1-8ad0-881538ebc3bb)
#### 这是监听`Haremsupervisor`时出现的错误
![_2509d34e2b63c6b00eb785355e1ac3f0_-1509458156_Screenshot_20230809_163447](https://github.com/diyigemt/arona/assets/89019933/a3cebffe-16b4-4ed5-937b-673e679641b0)
#### 这是`Haremsupervisor`在nga楼中的内容
![_aca3a8b4df83de501ab9e31abe4c84b2_-1741647378_Screenshot_20230809_163717_gov pianzong androidnga](https://github.com/diyigemt/arona/assets/89019933/87da77b6-88db-45fb-a738-6a0d5f190f40)
`nga.yml`的配置如下：
```yml
# 你自己的nga uid
uid: 4255XXXX
# 登录后产生的cookie, 可以从名叫"ngaPassportCid"的cookie中获取
cid: X9hign7ojuvmc95qbinss6uquucrnf77uqXXXXXX
# 扫描周期(单位min)
checkInterval: 30
# 数据源(主站寄了的时候可以换一下),可选"MAIN"(主站)和"SUB"(备用站)
source: SUB
# 要监听的发送者uid以及nga昵称
watch:
  42382305: xiwang399
  40785736: 安kuzuha
  64124793: 星泠鑫
  62698922: 深夜枕难眠
  61166973: 废9
  60347121: Haremsupervisor
  63850245: 船长的精英守卫
# 已发送的缓存
cache:
  - first: 29
    second: 705581576
  - first: 29
    second: 705581640
  - first: 29
    second: 705581624
  - first: 29
    second: 705581697
  - first: 29
    second: 705581662
  - first: 29
    second: 705581606
  - first: 30
    second: 705756066
  - first: 30
    second: 705755801
```
