### ISSUE TITLE
请求摸头的数组范例

### ISSUE THREAD

**Issue by KuraiKama** [diyigemt/arona#7]
请求摸头的数组范例，yml在线验证都是没问题的，但是加载之后就是各种报错，找不到问题在哪

**Comment by diyigemt** [comment]
emm， 不妨把报错的内容发出来?

**Comment by KuraiKama** [comment]
![_4}2_ 2Q~D6%SJ`LQP8YA_T](https://user-images.githubusercontent.com/32126258/221408001-64129960-d0ea-48e3-992a-bf8cf61b8b1c.png)
![%U S(V2}D R9DJRW8%X{4F](https://user-images.githubusercontent.com/32126258/221408006-9f2a8b6d-5ff2-4114-b67f-06244e841290.png)
![W)M0AX P YE_6{(H0BFB6UI](https://user-images.githubusercontent.com/32126258/221408144-d4130cee-bcdd-457a-ab5c-347f34eeaeae.png)

因为之前完全没接触过yml的编写，如果出现什么基础知识上的错误请好好指导一下orz

**Comment by diyigemt** [comment]
emmmm，是我的问题，应该是`message`而不是`String`的
马上更新文档(
```yaml
# 回复的消息
messageList: 
  - message: test
    weight: 1
# 事件优先级 从高到低可选 HIGHEST, HIGH, NORMAL, LOW, LOWEST, MONITOR
# 设置后需要重启插件生效
priority: HIGH
```
